# Generated by Django 6.0.1 on 2026-03-07 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100, verbose_name='Тип ошибки')),
                ('description', models.TextField(verbose_name='Описание ошибки')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('work_type', models.CharField(blank=True, max_length=20, verbose_name='Тип работы')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последнее появление')),
            ],
            options={
                'verbose_name': 'Статистика ошибок',
                'verbose_name_plural': 'Статистика ошибок',
            },
        ),
        migrations.CreateModel(
            name='GOSTTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('rules_json', models.JSONField(default=dict, help_text='Параметры ГОСТ: шрифт, размер, интервалы, отступы', verbose_name='Правила в формате JSON')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон ГОСТ',
                'verbose_name_plural': 'Шаблоны ГОСТ',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, verbose_name='Имя файла')),
                ('original_file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Исходный файл')),
                ('work_type', models.CharField(choices=[('coursework', 'Курсовая работа'), ('diploma', 'Дипломная работа'), ('lab', 'Лабораторная работа'), ('report', 'Отчёт по практике'), ('essay', 'Реферат')], default='coursework', max_length=20, verbose_name='Тип работы')),
                ('file_size', models.IntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('queued', 'В очереди'), ('parsing', 'Парсинг XML'), ('classifying', 'Классификация'), ('formatting', 'Форматирование'), ('completed', 'Завершено'), ('error', 'Ошибка')], default='uploaded', max_length=20, verbose_name='Статус обработки')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс (%)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/', verbose_name='Исправленный файл')),
                ('report_json', models.JSONField(default=dict, help_text='Список ошибок: [{type, element, was, became}]', verbose_name='Отчёт (JSON)')),
                ('total_elements', models.IntegerField(default=0, verbose_name='Всего элементов')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('warnings_count', models.IntegerField(default=0, verbose_name='Предупреждений')),
                ('headings_count', models.IntegerField(default=0, verbose_name='Заголовков')),
                ('paragraphs_count', models.IntegerField(default=0, verbose_name='Параграфов')),
                ('lists_count', models.IntegerField(default=0, verbose_name='Списков')),
                ('images_count', models.IntegerField(default=0, verbose_name='Изображений')),
                ('grade', models.CharField(default='', max_length=50, verbose_name='Оценка')),
                ('processing_time', models.FloatField(default=0, verbose_name='Время обработки (сек)')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обработки')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Результат обработки',
                'verbose_name_plural': 'Результаты обработки',
            },
        ),
    ]
